fix: bson corpus spec runner calling wrong fn
mongodb/js-bson pull request #436
Opened 2021-05-12 18:39 UTC by durran

I ran across this one-liner when looking into `Decimal128` usages.

2021-05-12 19:09 UTC, dariakp commented
@durran Looks good but I think per our convention, the commit message should be `test: ...` not `fix: ...` since we aren't fixing any functionality in the library itself

2021-05-14 20:52 UTC, emadum requested changes
The require for `Decimal128` at the top also needs to be removed, currently it's causing a lint error in CI

2021-05-24 17:23 UTC, nbbeeken approved these changes

2021-05-25 12:04 UTC, emadum approved these changes

2021-05-25 13:19 UTC, merged