chore(NODE-3330): added mocha.opts
mongodb/js-bson pull request #442
Opened 2021-06-17 15:27 UTC by andymina

## Description
- Added `mocha.opts` to `/test`

2021-06-17 15:57 UTC, emadum approved these changes

2021-06-17 16:12 UTC, nbbeeken requested changes
let's delete .mocharc.json here too, next time one of comes around here and needs to change options they'll probably think the json is the place to go but it will have no effect

2021-06-22 21:03 UTC, nbbeeken approved these changes

2021-06-23 14:30 UTC, dariakp approved these changes

2021-06-25 16:10 UTC, merged