Fix a long standing bug in Decimal128.fromString()
mongodb/js-bson pull request #458
Opened 2021-09-08 04:01 UTC by tzhuan

## Description

Fix a long standing bug in `Decimal128.fromString()`

  - https://github.com/mongodb/js-bson/issues/334
  - https://jira.mongodb.org/browse/NODE-3021

**What changed?**

The `representation` string was wrongly used to find the significant digits. The `digits` array should be used instead.

Note that the v2.0 and v3.0 branches also have this bug.

2021-09-08 15:25 UTC, dariakp requested changes
Thank you for submitting this fix, I just have a suggestion for a few more test cases around the leading/trailing zero

2021-09-08 15:25 UTC, dariakp commented on test/node/decimal128_tests.js
> +    expect(new Decimal128('-0.0011').toString()).to.equal('-0.0011');
```suggestion
    expect(new Decimal128('-0.0011').toString()).to.equal('-0.0011');
    expect(new Decimal128('-0.00110').toString()).to.equal('-0.00110');
    expect(new Decimal128('0.0011').toString()).to.equal('0.0011');
    expect(new Decimal128('0.00110').toString()).to.equal('0.00110');
```

2021-09-08 15:31 UTC, nbbeeken approved these changes
LGTM including the suggested tests, Thanks again!

2021-09-09 14:20 UTC, dariakp approved these changes

2021-09-09 14:20 UTC, merged

2021-09-10 02:18 UTC, tzhuan commented
Thank you!

Hope that you can make a new bson npm release (and also a new mongodb node driver npm release) as soon as possible because this bug is potentially a significant vulnerability especially for financial usages.

2021-09-10 18:41 UTC, dariakp commented
@tzhuan Yes, we are definitely planning to do a release soon. Thank you again!