Value check with null and undefined instead of truthiness
mongodb/js-bson pull request #477
Opened 2021-12-16 22:56 UTC by CPLepage

### Description
In the serializer, when it comes to check for an override value (`toBSON`), changing  the `value` check to compare with `null` and `undefined` instead of relying on the truthiness of `value`.

#### What is the motivation for this change?
Cannot extend BigInt prototype with`.toBSON()` since `0n === false`

trying to make this work
```ts
BigInt.prototype.toBSON = function() {
    return Long.fromBits(Number(this.valueOf() & BigInt(0xffffffff)),
        Number(this.valueOf() >> BigInt(32)))
}

// src/parser/serializer.ts:769
// Is there an override value
if(value && value.toBSON){
    // this won't go through if value === 0n
    ...
}

...

// then trows error here since value hasn't been overidden
// src/parser/serializer.ts:779
else if (typeof value === 'bigint') {
    throw new BSONTypeError('Unsupported type BigInt, please use Decimal128');
}
```

2021-12-17 15:58 UTC, nbbeeken requested changes
Hi @CPLepage, thanks so much for contributing here! I think this is something we would certainly want to fix. I've gone ahead and created a JIRA ticket to track the work and I have some suggestions of improvements for ya. If you get the chance adding a test of your usecase to: `test/node/to_bson_test.js` would be a great help. 

@dariakp @durran @baileympearson, Just wanna get y'all's attention here I'm suggesting we drop the throw case with toBSON not being of type 'function'. While very unlikely it seems wrong that our BSON library would not allow the document: `{ toBSON: 1 }` to be serialized. That being said we could easily keep it, and revisit that at a later time.

2021-12-17 15:58 UTC, nbbeeken commented on src/parser/serializer.ts
>        }
```suggestion
      if (typeof value?.toBSON === 'function') {
        value = value.toBSON();
      }
```

We can use the optional chaining syntax here to be a little more succinct, null and undefined will not be accessed with a dot so `typeof` will return `'undefined'` so the if statement won't be entered.

This is what it compiles to, just so we can all double check this is what's expected.
```js
typeof (value === null || value === undefined ? undefined : value.toBSON) === 'function'
```

2021-12-17 15:58 UTC, nbbeeken commented on src/parser/serializer.ts
>        }
```suggestion
      if (typeof value?.toBSON === 'function') {
        value = value.toBSON();
      }
```

2021-12-20 04:38 UTC, CPLepage commented
@nbbeeken good idea on the optional chaining, looks clean!<br />I added 2 tests on the current particular case. Let me know your thoughts

2021-12-20 19:04 UTC, nbbeeken commented
Hey @CPLepage do you mind if I push up some changes of my own here? due to our support for older node versions the testing arrangement can be kinda strange, I can make sure we still get bigint coverage on later versions of node 🙂

2021-12-20 19:05 UTC, CPLepage commented
@nbbeeken please go ahead! Tried a few things for the tests, but CI never passed

2021-12-20 19:32 UTC, nbbeeken approved these changes
@CPLepage  Let me know if you see anything I missed, I'll ask the team for a final look now 🙂  thanks again!

2021-12-20 19:44 UTC, CPLepage commented
@nbbeeken Looks good! Thanks to you for the quick replies!!

2022-01-04 16:54 UTC, baileympearson approved these changes

2022-01-04 19:33 UTC, dariakp approved these changes

2022-01-04 19:34 UTC, merged