feat!(NODE-4703): remove strict flag from parse and stringify
mongodb/js-bson pull request #535
Opened 2022-12-05 22:29 UTC by nbbeeken

### Description

#### What is changing?

Removing deprecated strict flag from EJSON

#### What is the motivation for this change?

Removing a deprecation

### Double check the following

- [x] Ran `npm run lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2022-12-06 15:40 UTC, durran requested changes

2022-12-06 15:40 UTC, durran commented on src/extended_json.ts
> +    options = { relaxed: true, legacy: false, ...options };
I'd prefer we don't mutate the input options here and assign to a new const.

2022-12-07 09:05 UTC, durran submitted a review, later dismissed

2022-12-07 14:41 UTC, baileympearson commented on docs/upgrade-to-v5.md
> +Extended JSON `parse` and `stringify` APIs ignore the deprecated `strict` option and it has been removed from the type definitions.
This is not clear.  Did they used to ignore the option or do they now?  We should make the difference between the old and new behaviors explicit.

Maybe something like:
```
In BSON 4x, the `strict` option is deprecated in the extended JSON `parse` and `stringify` functions.  

In BSON 5x, this option is removed.
```

2022-12-09 10:55 UTC, durran approved these changes

2022-12-09 11:36 UTC, merged