NODE(5056): Fix EJSON.parse bug
mongodb/js-bson pull request #562
Opened 2023-02-13 20:35 UTC by W-A-James

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-02-14 16:10 UTC, nbbeeken reviewed
sorry jumping on this early just noticed some things

2023-02-14 16:10 UTC, nbbeeken commented on src/extended_json.ts
> +      else throw new BSONRuntimeError('Unrecognized type for EJSON date');
```suggestion
      else throw new BSONRuntimeError(`Unrecognized type for EJSON date: ${typeof d}`);
```

2023-02-14 16:10 UTC, nbbeeken commented on src/error.ts
> +/** @public */
```suggestion
/**
 * An error generated when BSON functions encounter an unexpected input
 * or reaches an unexpected/invalid internal state
 *
 * @public
 * @category Error
 */
```

And can we add ` * @category Error` to the other errors while we're here, a little docs++

2023-02-15 20:08 UTC, W-A-James commented
Should we change the tsdoc comment for the `BSONError` class? At the moment it reads:

> `BSONError` objects are throw when runtime errors occur.

Having a subclass by the name of `BSONRuntimeError` seems confusing if that's what we have for the description of its parent class even if we specify that `BSONRuntimeError` specifically occurs when we have invalid internal state.

2023-02-15 20:27 UTC, nbbeeken commented
Sounds like a good improvement although there's still plenty of usage of it, someday we'll have descriptive errors as needed. We can make it more generic and omit the "runtime" bit. "thrown when BSON encounters an error" and then maybe an additional note about how it is the parent of all other errors we intentionally throw.

2023-02-15 22:33 UTC, nbbeeken requested changes

2023-02-15 22:33 UTC, nbbeeken commented on src/error.ts
> + * This is the parent calss for all the other errors thrown in this library.
```suggestion
 * This is the parent class for all the other errors thrown by this library.
```

2023-02-15 22:54 UTC, nbbeeken approved these changes

2023-02-16 14:08 UTC, baileympearson approved these changes

2023-02-16 14:10 UTC, merged