fix(NODE-5546): decimal 128 fromString performs inexact rounding (#613)
mongodb/js-bson pull request #621
Opened 2023-09-08 14:18 UTC by W-A-James

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-09-08 19:38 UTC, W-A-James commented
Blocking on #620

2023-09-11 18:22 UTC, nbbeeken commented
Should this be "feat"?

2023-09-11 21:12 UTC, nbbeeken requested changes
As expected some conflicts from the "fix" pr need resolving

2023-09-12 16:17 UTC, nbbeeken approved these changes

2023-09-12 18:04 UTC, merged