feat(NODE-5959): make byte parsing utils available on onDemand library
mongodb/js-bson pull request #662
Opened 2024-03-18 15:18 UTC by nbbeeken

### Description

#### What is changing?

- Adds utf and number parsing utils to onDemand

##### Is there new documentation needed for these changes?

No

#### What is the motivation for this change?

The driver can reuse the logic in these functions to implement a reviver.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [x] Changes are covered by tests
- [x] New TODOs have a related JIRA ticket

2024-03-18 20:19 UTC, aditi-khare-mongoDB requested changes

2024-03-18 20:19 UTC, aditi-khare-mongoDB commented on src/utils/byte_utils.ts
> + */
Can we add API docs to the `ByteUtils` type, to clarify what it encapsulates?

2024-03-18 20:19 UTC, aditi-khare-mongoDB commented on src/utils/number_utils.ts
> +export type NumberUtils = {
Can we add API docs to the `NumberUtils` type, to clarify what it encapsulates? Just a sentence or two.

2024-03-18 21:46 UTC, aditi-khare-mongoDB approved these changes

2024-03-19 19:08 UTC, W-A-James approved these changes

2024-03-19 20:00 UTC, merged